version: '3'
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    depends_on:
      - swag
    volumes:
      - /home/adez/docker-volumes/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    ports:
     - 9000:9000
     - 8000:8000

  home-assistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:latest
    depends_on:
      - swag
    volumes:
      - /home/adez/docker-volumes/homeassistant:/config
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt:/certs
      - /home/adez/docker-volumes/ha-openssl/openssl.cnf:/etc/ssl/openssl.cnf
    restart: always
    ports:
      - 8123:8123
      - 4199:4199
    devices:
      - /dev/serial/by-id/usb-RFXCOM_RFXtrx433XL_DO4GXDGW-if00-port0:/dev/ttyUSB1
      - /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AQ4MI444-if00-port0:/dev/ttyUSB0
 
  swag:
    container_name: swag
    image: ghcr.io/linuxserver/swag
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/adez/docker-volumes/secure-web-application-gateway:/config
    environment:
      - PGID=1000
      - PUID=1000
      - EMAIL=$SWAG_ENV_EMAIL
      - URL=$DUCKDNS_ENV_URL
      - SUBDOMAINS=$DUCKDNS_ENV_SUBDOMAINS
      - VALIDATION=http
      - TZ=Europe/Amsterdam
    ports:
      - 8080:80
      - 8443:443

  duckdns:
      container_name: duckdns
      image: ghcr.io/linuxserver/duckdns
      depends_on:
      - swag
      restart: unless-stopped
      volumes:
        - /home/adez/docker-volumes/duckdns/config:/config 
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Amsterdam
        - SUBDOMAINS=$DUCKDNS_ENV_SUBDOMAINS
        - TOKEN=$DUCKDNS_ENV_TOKEN

  # pihole:
  #   container_name: pihole
  #   image: pihole/pihole:latest
  #   depends_on:
  #     - swag
  #   restart: always
  #   ports:
  #     - "53:53/tcp"
  #     - "53:53/udp"
  #     - "67:67/udp"
  #     - "80:80/tcp"
  #     - "443:443/tcp"
  #   environment:
  #     - TZ=Europe/Amsterdam
  #     - WEBPASSWORD=$PI_HOLE_ENV_WEBPASSWORD
  #   volumes:
  #     - /home/adez/docker-volumes/pihole/pihole:/etc/pihole
  #     - /home/adez/docker-volumes/pihole/dnsmasq:/etc/dnsmasq.d
  #   dns:
  #     - 127.0.0.1
  #     - 8.8.8.8

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    depends_on:
      - swag
    restart: always
    volumes:
      - /home/adez/docker-volumes/mosquitto/config:/mosquitto/config
      - /home/adez/docker-volumes/mosquitto/data:/mosquitto/data
      - /home/adez/docker-volumes/mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001

  zigbee2mqtt:
    container_name: Zigbee2MQTT
    image: koenkk/zigbee2mqtt
    depends_on:
      - swag
    network_mode: host
    devices:
      - /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_662fa977371aec11968876e5f01c6278-if00-port0:/dev/ttyACM0
    restart: always
    volumes:
      - /home/adez/docker-volumes/zigbee2mqtt/data:/app/data
      - /etc/localtime:/etc/locatime:ro

  wireguard:
    container_name: wireguard
    image: lscr.io/linuxserver/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - SERVERURL=$WIREGUARD_ENV_URL
      - SERVERPORT=$WIREGUARD_ENV_SERVER_PORT
      - PEERS=laptop,phone
      - PEERDNS=auto       
    volumes:
      - /home/adez/docker-volumes/wireguard/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: always